image: python:3.5

stages:
  - tests
  - build

tests:
  stage: tests
  script:
    - pip install pytest -r requirements.txt
    - pytest
  artifacts:
    reports:
      junit: report.xml

build:
  stage: build
  script:
    - pip install devpi-client
    - devpi use http://devpi.oncoworkers.oncodna.com
    - devpi login root --password=''
    - devpi use root/public
    - devpi upload --only-latest

  only:
    refs:
      - master
    changes:
      - bioit_module/__version__.py

  artifacts:
    paths:
      - dist
    expire_in: 1 week